name: 'Rspec reporter'
description: 'Report Rspec result on Pull Request comment'
branding:
  icon: check-square
  color: purple
inputs:
  filepath:
    description: 'Output file path of rspec'
    required: true
  report-mode:
    description: 'Rspec report mode. Supported mode is `default`, `onlyPRFiles`'
    required: false
    default: 'default'
  test-framework:
    description: 'test framework(rspec)'
    required: true
    default: 'rspec'
runs:
  using: 'node20'
  main: 'dist/index.js'
