name: 'Rspec reporter'
description: 'Report Rspec result on Pull Request comment'
branding:
  icon: check-square
  color: purple
inputs:
  filepath:
    description: 'Output file path of rspec'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'
